name: Tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  analyze:
    name: Codecov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm 8
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: pnpm i

      - name: Run Tests
        run: pnpm turbo test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.6.0
        with:
          fail_ci_if_error: true
          directory: ./packages/nemo/coverage
          token: ${{ secrets.CODECOV_TOKEN }}
